### DISCUSSION TITLE
使用 mosdns 将所有域名解析的 Cloudflare IP 重定向至最快 IP

### DISCUSSION THREAD

**Discussion by Auska** [XIU2/CloudflareSpeedTest#317] [分享]
[https://github.com/IrineSistiana/mosdns](https://github.com/IrineSistiana/mosdns)
mosdns 是一个可以自由控制的 DNS 转发器，可以实现根据域名解析 IP 来修改为自定义 IP，因此适合用来将所有套了 Cloudflare CDN 的域名都给强制解析为优选 IP（包括 AWS Cloudfront、Akamai CDN 都可以这样干）。

> 目前 v5 大版本刚出来，改动较大，也可能不太稳定，因此我还没用上。

以下为配置文件示例，我自己用的是 v4.x 最后一个版本。

## \# 配置文件（此为 v4.x 版本）

- 下载： https://github.com/IrineSistiana/mosdns/releases/tag/v4.5.3  
- 教程： https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v4

``` yaml
# 日志
log:
  level: info # 日志级别，可选 debug 、 info 、 warn 、 error 。默认 info
  file: "/tmp/mosdns.log" # 留空代表不输出日志


# 服务器
servers:
  - exec: main_sequence # 本服务器运行插件的 tag
    listeners:
      - protocol: udp # 即可以通过 UDP 方式访问该 DNS
        addr: ":53" # 53 端口


# 插件
plugins:

# 缓存
  - tag: lazy_cache
    type: cache
    args:
      size: 1024 # 缓存条数
      lazy_cache_ttl: 86400 # 缓存时间
      lazy_cache_reply_ttl: 30 # 返回过期应答的 TTL

# 转发到上游 DNS
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: "udp://114.114.114.114" # 114 公共明文 UDP DNS
        - addr: "udp://223.5.5.5" # 阿里云的明文 UDP DNS
        - addr: "https://dns.alidns.com/dns-query" # 阿里的 DoH 加密 DNS
          idle_timeout: 30 # 连接复用空连接保持时间，单位: 秒
          trusted: true # 是否是可信服务器
        - addr: "https://doh.pub/dns-query" # 腾讯的 DoH 加密 DNS
          idle_timeout: 30
          trusted: true

# 匹配 Cloudflare CDN IP 地址
  - tag: response_IP_Cloudflare
    type: response_matcher
    args:
      ip:
        - "1.1.1.0/24"
        - "1.0.0.0/24"
        - "162.158.0.0/15"
        - "104.16.0.0/12"
        - "172.64.0.0/13"
#        - "2606:4700::/32" # 如果要匹配 IPv6 地址，则请移除行首第一个井号

# 匹配 Cloudflare CDN CNAME
  - tag: response_CNAME_Cloudflare
    type: response_matcher
    args:
      cname:
        - "domain:cdn.cloudflare.net"

# 修改 IP 为自选 IP
  - tag: blackhole_Cloudflare
    type: blackhole
    args:
      ipv4: "127.0.0.1" # 如果请求类型是 A，则生成 IP 为该地址的应答。请修改为自选 IPv4
#      ipv6: "xxxx:xxxx:xxxx:xxxx" # 如果请求类型是 AAAA，则生成 IP 为该地址的应答。请修改为自选 IPv6，如果要返回 IPv6 则请移除行首第一个井号

# 将多个插件组合成流水线
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - lazy_cache # 匹配缓存
        - forward_local               # 请求转发至上游 DNS
        - if: response_CNAME_Cloudflare || response_IP_Cloudflare # 如果域名解析结果为 Cloudflare CDN 地址
          exec:
            - blackhole_Cloudflare # 则返回指定的 自选 IP 
  ```

另外通过 mosdns 接管 dns 这种方式，是比较方便的为代理，比如 OpenClash 进行分流的。

****

## \# 配置文件（此为 v3.x 版本）：

- 下载： https://github.com/IrineSistiana/mosdns/releases/tag/v3.9.0

<details>
<summary><kbd><strong>「 点击展开 查看内容 」</strong></kbd></summary>

****

``` yaml
log:
  level: info

plugin:

  ################# 服务插件 ################

  # 启动服务器的插件
  - tag: main_server
    type: server
    args:
      entry:
        - _default_cache  # 启用缓存
        - main_sequence   # 分流逻辑
      server:       # 监听地址与协议。可按序增减。
        - protocol: udp
          addr: "127.0.0.1:53"    #请自行修改合适端口

  ################# 可执行插件 ################

  # 包含分流的逻辑的插件
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - forward_local               # 先请求转发至本地服务器
        - if:
            - response_IP_Cloudflare # 如果域名解析结果为 Cloudflare CDN IP 地址
          exec:
            - blackhole_Cloudflare # 则返回指定的 自选 IP 

  # 转发请求至本地服务器的插件
  - tag: forward_local
    type: forward
    args:
      upstream:
        - addr: 114.114.114.114

  - tag: blackhole_Cloudflare
    type: blackhole
    args:
      ipv4: "127.0.0.1" # 如果请求类型是 A，则生成 IP 为该地址的应答。请修改为自选 IPv4。
#      ipv6: "xxxx:xxxx:xxxx:xxxx"     # 如果请求类型是 AAAA，则生成 IP 为该地址的应答。请修改为自选 IPv6，如果要返回 IPv6 则请移除行首第一个井号

  ################ 匹配器插件 #################

  # 匹配 IP 的插件
  - tag: response_IP_Cloudflare
    type: response_matcher
    args:
      ip:
        - "1.1.1.0/24"
        - "1.0.0.0/24"
        - "162.158.0.0/15"
        - "104.16.0.0/12"
        - "172.64.0.0/13"
#        - "2606:4700::/32" # 如果要匹配 IPv6 地址，则请移除行首第一个井号
```

</details>

**Comment by orency** [comment]
其实cloudfront和akamai也可以这么玩,把默认的ntt线路垃圾ipv4替换成香港或东京的cn2线路ipv4,可以达到起飞的效果,ipv6更佳.
唯一问题是akaimai没做全证书绑定,会显示证书错误,需要手动忽略

**Comment by 120318** [comment]
已合并至 1L 。

**Comment by GD2021** [comment]
mosdns这样配置好的话，还需要下载CloudflareSpeedTest嘛？

**Comment by XIU2** [comment]
@GD2021 mosdns 只是负责把所有套了 Cloudflare CDN 的域名解析 IP 修改为 **自选 IP** 罢了。
而这个**自选 IP**，还需要依靠 CloudflareST 来本地测速获得，并修改 mosdns 配置文件里的目标 IP。

**Comment by Cirn09** [comment]
写了套 5.x 版本的配置：
```
# 复杂且易拓展的
log:
  level: info
plugins:
  - tag: query
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: 1.1.1.1
        - addr: 8.8.8.8

  - tag: lazy_cache
    type: cache
    args:
      size: 1024
      lazy_cache_ttl: 86400

  - tag: cf_ips
    type: ip_set
    args:
      files: /etc/cf_ips # 将 ip.txt 重命名放在 /etc 下

  - tag: seq
    type: sequence
    args:
      - exec: $lazy_cache
      - exec: $query
      - matches: resp_ip $cf_ips
        exec: black_hole 127.0.0.1 # 自行修改为最优 IP

  - tag: udp_server
    type: udp_server
    args:
      entry: seq
      listen: 0.0.0.0:53 # 只给本机用的话，记得改成 127.0.0.1:53
```

```
# 简单版
log:
  level: info
plugins:
  - tag: seq
    type: sequence
    args:
      - exec: cache 1024
      - exec: forward 114.114.114.114
      - matches: resp_ip &/etc/cf_ips
        exec: black_hole 127.0.0.1 # 自行修改为最优 IP

  - tag: udp_server
    type: udp_server
    args:
      entry: seq
      listen: 0.0.0.0:53 # 只给本机用的话，记得改成 127.0.0.1:53
```

**Reply by Nekopazo** [reply]
这个确实不错，不过没有添加ipv6的设置

**Reply by lonelylose** [reply]
不错，忘记更新了，查了文档，ipv6也要替换的话只需要在这里加上优选ipv6地址就可以了

**Comment by IMANCF** [comment]
如何将服务器的 IP 转换为 Cloudflare 的 IP?
请您指导我或提供相关的 GitHub 链接.谢谢.

**Reply by 152952849** [reply]
https://github.com/hansyao/breakwall

**Comment by ghost** [comment]
有哪位大佬能帮我看看我的配置文件，不知道为什么就是跑不起来，5.x

```
# mosdns v5.1.3 配置文件

# 日志设置
logger:
  file: mosdns.log # 日志文件名，可以自定义
  level: info # 日志级别，可以是debug, info, warn, error, fatal
  encoding: console # 日志格式，可以是console或json
  production: true # 纯json输出，更简洁和规范

# 服务器设置
server:
  - tag: main_server # 服务器标签，可以自定义
    type: udp # 服务器类型，可以是udp或tcp
    addr: :53351 # 监听地址和端口，冒号前面可以留空或填写本机ip
  - tag: main_server_tcp # 添加一个tcp类型的服务器，支持更大的请求和应答
    type: tcp 
    addr: :53351 

# 上游dns服务器
upstream:
  - tag: upstream_dns
    type: udp
    addr: 192.168.1.1:53350
  - tag: upstream_dns2 # 添加一个备用的上游dns服务器，使用tls协议加密传输
    type: dot 
    addr: 8.8.8.8:853 
    idle_timeout: 10s # 设置空闲超时时间为10秒，节省资源
    max_conns: 5 # 设置最大连接数为5，避免过载
  - tag: upstream_dns3 # 添加另一个备用的上游dns服务器，使用https协议加密传输
    type: doh 
    url: https://cloudflare-dns.com/dns-query 
    idle_timeout: 10s 
    max_conns: 5 
    policy: parallel # 设置负载均衡策略为parallel，即并发查询所有上游dns服务器，并选择最快的应答

# ip段文件
ip_list:
  - tag: ip_ilop
    file: /root/cf.txt # 这个文件需要自己创建，包含ilop的ip段，每行一个
  - tag: ip_github
    file: /root/github.txt # 这个文件需要自己创建，包含github.com的多个ip，每行一个

# 插件列表
plugin:
  # 使用hosts插件来指定域名和ip的映射关系，更简单和高效
  - tag: hosts_plugin 
    type: hosts 
    args:
      hosts:
        github.com.: ip_github # 随机选择一个ip返回

  # 使用fallback插件来从多个上游dns服务器中选择最佳的应答，更灵活和智能
  - tag: fallback_plugin 
    type: fallback 
    args:
      upstreams:
        - upstream_dns 
        - upstream_dns2 
        - upstream_dns3 
      fastest_idle_timeout: 0s # 设置最快模式的空闲超时时间为0秒，即始终使用最快模式

# 执行顺序
sequence:
  - if:
      - query_is_type(A) # 只处理A记录查询
    exec:
      - match_plugin # 使用match插件来组合多个条件，并指定匹配后执行的插件

# 匹配插件设置
match_plugin:
  type: match 
  args:
    exec_if_match:
      - rewrite_ilop # 如果结果中的A记录为ilop的ip段，则替换为192.135.98
      - hosts_plugin # 如果请求的域名为github.com，则从ip_github中随机选择一个ip返回
      - fallback_plugin # 如果都不匹配，则使用fallback插件查询上游dns服务器并选择最佳应答
```
