### ISSUE TITLE
利用mosdns项目实现返回测速CDN

### ISSUE THREAD

**Issue by Auska** [XIU2/CloudflareSpeedTest#115]
[https://github.com/IrineSistiana/mosdns/wiki/Plugin#%E5%8C%B9%E9%85%8D%E5%99%A8%E6%8F%92%E4%BB%B6](url)
配置文件：
`log:
  level: info

plugin:

  ################# 服务插件 ################

  # 启动服务器的插件
  - tag: main_server
    type: server
    args:
      entry:
        - _default_cache  # 启用缓存
        - main_sequence   # 分流逻辑
      server:       # 监听地址与协议。可按序增减。
        - protocol: udp
          addr: '127.0.0.1:1253'    #请自行修改合适端口

  ################# 可执行插件 ################

  # 包含分流的逻辑的插件
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - forward_local               # 先请求转发至本地服务器
        - if:
            - response_has_ip   # 如果应答包含 IP
          exec:
            - cdn                    # 就直接采用CDN测速结果

  # 转发请求至本地服务器的插件
  - tag: forward_local
    type: forward
    args:
      upstream:
        - addr: 114.114.114.114

  - tag: 'cdn'
    type: 'blackhole'
    args:
      ipv4: '127.0.0.1' # 如果请求类型是 A，则生成 IP 为该地址的应答。请修改为自己的CDN测速结果。
      ipv6: '::1'     # 如果请求类型是 AAAA，则生成 IP 为该地址的应答。请修改为自己的CDN测速结果。

  ################ 匹配器插件 #################

  # 匹配 IP 的插件
  - tag: response_has_ip
    type: response_matcher
    args:
      ip:
        - '1.1.1.0/24'
        - '1.0.0.0/24'
        - '1.1.1.1/32'
        - '1.0.0.1/32'
        - '103.21.244.0/22'
        - '103.22.200.0/22'
        - '103.31.4.0/22'
        - '104.16.0.0/13'
        - '104.24.0.0/14'
        - '108.162.192.0/18'
        - '131.0.72.0/22'
        - '141.101.64.0/18'
        - '162.158.0.0/15'
        - '172.64.0.0/13'
        - '173.245.48.0/20'
        - '188.114.96.0/20'
        - '190.93.240.0/20'
        - '197.234.240.0/22'
        - '198.41.128.0/17'
        - '2606:4700:10::6814:0/112'
        - '2606:4700:10::ac43:0/112'
        - '2606:4700:3000::/48'
        - '2606:4700:3001::/48'
        - '2606:4700:3002::/48'
        - '2606:4700:3003::/48'
        - '2606:4700:3004::/48'
        - '2606:4700:3005::/48'
        - '2606:4700:3006::/48'
        - '2606:4700:3007::/48'
        - '2606:4700:3008::/48'
        - '2606:4700:3009::/48'
        - '2606:4700:3010::/48'
        - '2606:4700:3011::/48'
        - '2606:4700:3012::/48'
        - '2606:4700:3013::/48'
        - '2606:4700:3014::/48'
        - '2606:4700:3015::/48'
        - '2606:4700:3016::/48'
        - '2606:4700:3017::/48'
        - '2606:4700:3018::/48'
        - '2606:4700:3019::/48'
        - '2606:4700:3020::/48'
        - '2606:4700:3021::/48'
        - '2606:4700:3022::/48'
        - '2606:4700:3023::/48'
        - '2606:4700:3024::/48'
        - '2606:4700:3025::/48'
        - '2606:4700:3026::/48'
        - '2606:4700:3027::/48'
        - '2606:4700:3028::/48'
        - '2606:4700:3029::/48'
        - '2606:4700:3030::/48'
        - '2606:4700:3031::/48'
        - '2606:4700:3032::/48'
        - '2606:4700:3033::/48'
        - '2606:4700:3034::/48'
        - '2606:4700:3035::/48'
        - '2606:4700:3036::/48'
        - '2606:4700:3037::/48'
        - '2606:4700:3038::/48'
        - '2606:4700:3039::/48'`

**Comment by IrineSistiana** [comment]
这想法好啊。可以安排成一个插件。

**Comment by orency** [comment]
其实cloudfront和akamai也可以这么玩,把默认的ntt线路垃圾ipv4替换成香港或东京的cn2线路ipv4,可以达到起飞的效果,ipv6更佳.
唯一问题是akaimai没做全证书绑定,会显示证书错误,需要手动忽略

**Comment by getupbuzz** [comment]
对于新版的mosdns，上面的配置会存在语法问题，新版的配置如下（这里只保留了ipv4相关）：
```
log:
  level: info
  file: "/tmp/mosdns.log"
servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: ":5335"
      - protocol: tcp
        addr: ":5335"
plugins:
  - tag: lazy_cache
    type: cache
    args:
      size: 1024
      lazy_cache_ttl: 86400
      lazy_cache_reply_ttl: 30
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: "udp://114.114.114.114"
        - addr: "udp://223.5.5.5"
        - addr: "https://dns.alidns.com/dns-query"
          idle_timeout: 30
          trusted: true
        - addr: "https://doh.pub/dns-query"
          idle_timeout: 30
          trusted: true
  - tag: response_has_ip
    type: response_matcher
    args:
      ip:
        - '1.1.1.0/24'
        - '1.0.0.0/24'
        - '1.1.1.1/32'
        - '1.0.0.1/32'
        - '103.21.244.0/22'
        - '103.22.200.0/22'
        - '103.31.4.0/22'
        - '104.16.0.0/13'
        - '104.24.0.0/14'
        - '108.162.192.0/18'
        - '131.0.72.0/22'
        - '141.101.64.0/18'
        - '162.158.0.0/15'
        - '172.64.0.0/13'
        - '173.245.48.0/20'
        - '188.114.96.0/20'
        - '190.93.240.0/20'
        - '197.234.240.0/22'
        - '198.41.128.0/17'
  - tag: 'cdn'
    type: 'blackhole'
    args:
      ipv4: '127.0.0.1' # 如果请求类型是 A，则生成 IP 为该地址的应答。请修改为自己的CDN测速结果。

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - lazy_cache
        - forward_local               # 先请求转发至本地服务器
        - if: "response_has_ip"   # 如果应答包含 IP
          exec:
            - cdn                    # 就直接采用CDN测速结果
  ```

另外通过mosdns接管dns这种方式，是比较方便的为代理，比如OpenClash进行分流的。
